
name: Create release
on: 
  workflow_dispatch:
    inputs: 
      version: 
        type: text
        description: 'Version number Eg: 4.2.0' 

jobs:
  build-linux:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout 
      uses: actions/checkout@v2
    - name: Configure
      run: |
        sudo apt-get update
        sudo apt-get install -y -f \
        libgtk-3-dev \
        libwebkit2gtk-4.0-37 \
        libwebkit2gtk-4.0-dev \
        libayatana-appindicator3-dev
    - name: Build
      run: ./scripts/bz.py
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: linux_binary
        path: bin/neutralino-linux_x64

  build-arm64:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build package
        uses: uraimo/run-on-arch-action@v2
        id: build-package
        with:
          arch: aarch64
          distro: ubuntu18.04
          install: |
            apt-get update
            apt-get install -y -f \
            libgtk-3-dev \
            libwebkit2gtk-4.0-37 \
            libwebkit2gtk-4.0-dev \
            libayatana-appindicator3-dev \
            curl \
            git \
            python3 \
            g++ \
            make \
            gcc \
            pkg-config
          githubToken: ${{ github.token }}
          run: ./scripts/bz.py
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: arm64_binary
          path: bin/neutralino-linux_arm64

  build-windows:
    runs-on: windows-latest
    steps:
    - name: Checkout 
      uses: actions/checkout@v2
    - name: Build
      run: python ./scripts/bz.py
      shell: cmd
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: win_binary
        path: bin/neutralino-win_x64.exe

  build-darwin:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: ./scripts/bz.py
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: darwin_binary
        path: bin/neutralino-mac_x64
        
  create-release:
    needs: [build-linux, build-arm64, build-windows, build-darwin]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 
      uses: actions/checkout@v2
      
    - name: Clean previous binaries
      run: |
        rm -f \
        ./bin/neutralino-linux_x64 \
        ./bin/neutralino-linux_arm64 \
        ./bin/neutralino-win_x64.exe \
        ./bin/neutralino-mac_x64
        
    - name: Download Linux build artifacts 
      uses: actions/download-artifact@v2
      with:
        name: linux_binary
        path: ./bin

    - name: Download Arm64 build artifacts
      uses: actions/download-artifact@v2
      with:
        name: arm64_binary
        path: ./bin

    - name: Download Windows build artifacts
      uses: actions/download-artifact@v2
      with:
        name: win_binary
        path: ./bin
        
    - name: Download Darwin build artifacts 
      uses: actions/download-artifact@v2
      with:
        name: darwin_binary
        path: ./bin
        
    - name: Create Release zip
      uses: vimtor/action-zip@v1
      with:
        files: ./bin/neutralino-linux_x64 ./bin/neutralino-linux_arm64 ./bin/neutralino-win_x64.exe ./bin/neutralino-mac_x64 ./bin/WebView2Loader.dll
        dest: './bin/neutralinojs-v${{github.event.inputs.version}}.zip'
        
    - name: Create Release Notes
      run: |
        chmod +x ./scripts/rz.py
        ./scripts/rz.py create ${{github.event.inputs.version}}
        
    - name: Commit and Push Changelog
      uses: EndBug/add-and-commit@v7.4.0
      with:
        default_author: github_actions
        message: 'Update changelog for v${{github.event.inputs.version}}' 
        add: 'CHANGELOG.md'
        tag: v${{github.event.inputs.version}}
        
    - name: Create Branch
      uses: peterjgrainger/action-create-branch@v2.0.1
      with: 
        branch: v${{github.event.inputs.version}}
      env:
        GITHUB_TOKEN: ${{ secrets.COMMIT_TOKEN }}
        
    - name: Create a GitHub release
      uses: ncipollo/release-action@v1
      with:
          tag: v${{github.event.inputs.version}}
          name: Neutralinojs v${{github.event.inputs.version}} released!
          bodyFile: ./.tmprz/release_notes.md
          artifacts: './bin/neutralinojs-v${{github.event.inputs.version}}.zip'
          
    - name: Clean Release Notes
      run: |
        ./scripts/rz.py cleanup
        
    - name: Send Discord Notification
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      uses: Ilshidur/action-discord@master
      with:
        args: |
          Neutralinojs v${{github.event.inputs.version}} released ðŸš€
          Changelog: https://github.com/neutralinojs/neutralinojs/releases/tag/v${{github.event.inputs.version}}
