name: Nightly release
on: 
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *

jobs:
  build-linux:
    runs-on: ubuntu-22.04

    container:
      image: ubuntu:20.04
      env:
        DEBIAN_FRONTEND: noninteractive
        GIT_DISCOVERY_ACROSS_FILESYSTEM: 1

    strategy:
      matrix:
        include:
          - arch: amd64
            toolchain: ''
            neuarch: 'x64'
          - arch: arm64
            toolchain: '-DCMAKE_TOOLCHAIN_FILE=cmake/toolchains/linux-aarch64.cmake'
            neuarch: 'arm64'
          - arch: armhf
            toolchain: '-DCMAKE_TOOLCHAIN_FILE=cmake/toolchains/linux-armhf.cmake'
            neuarch: 'armhf'

    steps:
    - name: Checkout 
      uses: actions/checkout@v3

    - name: Setup cross-compile
      if: ${{ matrix.arch == 'arm64' || matrix.arch == 'armhf' }}
      run: |
        dpkg --add-architecture ${{ matrix.arch }}
        mv /etc/apt/sources.list /etc/apt/sources.list.amd64.bak

        tee /etc/apt/sources.list <<'EOF'
        deb [arch=amd64] http://archive.ubuntu.com/ubuntu jammy main universe multiverse restricted
        deb [arch=amd64] http://archive.ubuntu.com/ubuntu jammy-updates main universe multiverse restricted
        deb [arch=amd64] http://archive.ubuntu.com/ubuntu jammy-security main universe multiverse restricted

        deb [arch=${{ matrix.arch }}] http://ports.ubuntu.com/ubuntu-ports jammy main universe multiverse restricted
        deb [arch=${{ matrix.arch }}] http://ports.ubuntu.com/ubuntu-ports jammy-updates main universe multiverse restricted
        deb [arch=${{ matrix.arch }}] http://ports.ubuntu.com/ubuntu-ports jammy-security main universe multiverse restricted
        EOF

    - name: Install amd64 dependencies
      if: ${{ matrix.arch == 'amd64' }}
      run: |
        apt-get update
        apt-get install -y -f \
          g++ \
          libgtk-3-dev \
          libwebkit2gtk-4.0-dev

    - name: Install arm64 toolchains and dependencies
      if: ${{ matrix.arch == 'arm64' }}
      run: |
        apt-get clean
        apt-get update
        apt-get install -y \
          gcc-aarch64-linux-gnu g++-aarch64-linux-gnu \
          libgtk-3-dev:arm64 libwebkit2gtk-4.0-dev:arm64

    - name: Install arm64 toolchains and dependencies
      if: ${{ matrix.arch == 'armhf' }}
      run: |
        apt-get clean
        apt-get update
        apt-get install -y \
          gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf \
          libgtk-3-dev:armhf libwebkit2gtk-4.0-dev:armhf

    - name: Install common dependencies
      run: |
        apt-get update
        apt-get install -y -f \
          pkg-config \
          git \
          cmake \
          ninja-build
    
    - name: Build ${{ matrix.arch }}
      run: |
        git config --global --add safe.directory $GITHUB_WORKSPACE
        mkdir -p build
        cmake -DCMAKE_BUILD_TYPE=Release . -G Ninja -B build ${{ matrix.toolchain }}
        ninja -C build -j$(nproc)
      
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4.4.0
      with:
        name: linux_${{ matrix.neuarch }}_binary
        path: |
          bin/neutralino-linux_${{ matrix.neuarch }}

  build-windows:
    runs-on: windows-2022
    steps:
    - name: Checkout 
      uses: actions/checkout@v3
    - name: Build
      run: python ./scripts/bz.py
      shell: cmd
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4.4.0
      with:
        name: win_binary
        path: bin/neutralino-win_x64.exe

  build-darwin:
    runs-on: macos-14
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build arm64
      run: |
        mkdir -p build
        cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_OSX_ARCHITECTURES=arm64 . -G Ninja -B build
        ninja -C build

    - name: Build x64
      run: |
        rm -fr build
        mkdir -p build
        cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_OSX_ARCHITECTURES=x86_64 . -G Ninja -B build
        ninja -C build
    
    - name: Merge universal
      run: |
        lipo bin/neutralino-mac_x64 bin/neutralino-mac_arm64 -create -output bin/neutralino-mac_universal

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4.4.0
      with:
        name: darwin_binary
        path: |
          bin/neutralino-mac_x64
          bin/neutralino-mac_arm64
          bin/neutralino-mac_universal
        
  update-nightly-release:
    needs: [build-linux, build-windows, build-darwin]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 
      uses: actions/checkout@v3
      
    - name: Delete nightly tag
      uses: dev-drprasad/delete-tag-and-release@v1.0
      with:
        tag_name: nightly
        github_token: ${{ secrets.COMMIT_TOKEN }}
        
    - name: Download Linux build artifacts 
      uses: actions/download-artifact@v4.1.7
      with:
        name: linux_x64_binary
        path: ./bin
        
    - name: Download Linux build artifacts 
      uses: actions/download-artifact@v4.1.7
      with:
        name: linux_arm64_binary
        path: ./bin
        
    - name: Download Linux build artifacts 
      uses: actions/download-artifact@v4.1.7
      with:
        name: linux_armhf_binary
        path: ./bin

    - name: Download Windows build artifacts
      uses: actions/download-artifact@v4.1.7
      with:
        name: win_binary
        path: ./bin
        
    - name: Download Darwin build artifacts 
      uses: actions/download-artifact@v4.1.7
      with:
        name: darwin_binary
        path: ./bin
        
    - name: Create Release zip
      uses: vimtor/action-zip@v1
      with:
        files: ./bin/neutralino-linux_x64 ./bin/neutralino-linux_arm64 ./bin/neutralino-linux_armhf ./bin/neutralino-win_x64.exe ./bin/neutralino-mac_x64 ./bin/neutralino-mac_arm64 ./bin/neutralino-mac_universal ./bin/WebView2Loader.dll
        dest: './bin/neutralinojs-nightly.zip'
        
    - name: Create Release Notes
      run: |
        chmod +x ./scripts/rz.py
        ./scripts/rz.py create nightly --no-changes --top=":warning: **Nightly build**: This nighly-release may contain experimental features and breaking changes."
        
    - name: Update nightly GitHub release
      uses: ncipollo/release-action@v1
      with:
          name: Neutralinojs nightly release
          bodyFile: ./.tmprz/release_notes.md
          artifacts: ./bin/neutralinojs-nightly.zip
          prerelease: true
          allowUpdates: true
          tag: nightly
          
    - name: Clean Release Notes
      run: |
        ./scripts/rz.py cleanup
